import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {
  ADMIN: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.CREATE_BLOG,
    PERMISSIONS.EDIT_BLOG,
    PERMISSIONS.DELETE_BLOG,
  ],

  PUBLISHER: [
    PERMISSIONS.CREATE_BLOG,
    PERMISSIONS.EDIT_BLOG,
  ],

  USER: [  PERMISSIONS.DELETE_USER],
} as const;


export type Role = keyof typeof ROLE_PERMISSIONS;

export type RolePermission =
  (typeof ROLE_PERMISSIONS)[Role][number];
